<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

header('Content-Type: application/json');

$limit = isset($_GET['limit']) ? $_GET['limit'] : 5;
$page = isset($_GET['page']) ? $_GET['page'] : 1;


$client = new \Github\Client();

$api = new \Sumeet\GithubUser($client);

$api->setPerPage($limit);

$paginator = new \Github\ResultPager($client);

$data = $paginator->fetch($api, 'repositories', ['symfony', 'owner', 'full_name','asc', $page]);

echo json_encode(['data'=>$data]);

?>
